// This file was auto-generated by Fern from our API Definition.

import type * as core from "../../../../../core/index.js";

/**
 * @example
 *     {
 *         "Idempotency-Key": "550e8400-e29b-41d4-a716-446655440000"
 *     }
 */
export interface CreateJobRequest {
    /** Required deduplication key (max 256 chars). Reusing the same key within 24 hours replays the stored successful response (200/202). Error responses (4xx/5xx) are never stored, so a failed request can be retried safely with the same key. */
    "Idempotency-Key": string;
    /** PDF file to remediate */
    file?: core.file.Uploadable | undefined;
    /** Optional callback URL for HMAC-signed completion webhook */
    webhook_url?: string;
}
