// This file was auto-generated by Fern from our API Definition.

import type * as core from "../../../../../core/index.js";

/**
 * @example
 *     {
 *         "Idempotency-Key": "550e8400-e29b-41d4-a716-446655440000"
 *     }
 */
export interface CreateJobRequest {
    /** Deduplication key — reused within 24h returns the stored response */
    "Idempotency-Key"?: string;
    /** PDF file to remediate */
    file?: core.file.Uploadable | undefined;
    /** Optional callback URL for HMAC-signed completion webhook */
    webhook_url?: string;
}
