// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface GetJobResultRequest {
    /** Job identifier from POST /v1/jobs response */
    id: string;
}
