// This file was auto-generated by Fern from our API Definition.

import type * as A11yfy from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface ListJobsRequest {
    /** Page size (1–100, default 20) */
    limit?: number;
    /** Opaque pagination cursor from a previous response */
    cursor?: string;
    /** Filter by job status */
    status?: A11yfy.ListJobsRequestStatus;
}
