// This file was auto-generated by Fern from our API Definition.

import { BillingClient } from "./api/resources/billing/client/Client.js";
import { CertificatesClient } from "./api/resources/certificates/client/Client.js";
import { JobsClient } from "./api/resources/jobs/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "./BaseClient.js";
import * as core from "./core/index.js";

export declare namespace A11yfyClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class A11yfyClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<A11yfyClient.Options>;
    protected _jobs: JobsClient | undefined;
    protected _billing: BillingClient | undefined;
    protected _certificates: CertificatesClient | undefined;

    constructor(options: A11yfyClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get jobs(): JobsClient {
        return (this._jobs ??= new JobsClient(this._options));
    }

    public get billing(): BillingClient {
        return (this._billing ??= new BillingClient(this._options));
    }

    public get certificates(): CertificatesClient {
        return (this._certificates ??= new CertificatesClient(this._options));
    }

    /**
     * Make a passthrough request using the SDK's configured auth, retry, logging, etc.
     * This is useful for making requests to endpoints not yet supported in the SDK.
     * The input can be a URL string, URL object, or Request object. Relative paths are resolved against the configured base URL.
     *
     * @param {Request | string | URL} input - The URL, path, or Request object.
     * @param {RequestInit} init - Standard fetch RequestInit options.
     * @param {core.PassthroughRequest.RequestOptions} requestOptions - Per-request overrides (timeout, retries, headers, abort signal).
     * @returns {Promise<Response>} A standard Response object.
     */
    public async fetch(
        input: Request | string | URL,
        init?: RequestInit,
        requestOptions?: core.PassthroughRequest.RequestOptions,
    ): Promise<Response> {
        return core.makePassthroughRequest(
            input,
            init,
            {
                baseUrl: this._options.baseUrl ?? this._options.environment,
                headers: this._options.headers,
                timeoutInSeconds: this._options.timeoutInSeconds,
                maxRetries: this._options.maxRetries,
                fetch: this._options.fetch,
                logging: this._options.logging,
                getAuthHeaders: async () => (await this._options.authProvider.getAuthRequest()).headers,
            },
            requestOptions,
        );
    }
}
