// This file was auto-generated by Fern from our API Definition.

export const A11yfyEnvironment = {
    Default: "https://a11yfy.com",
} as const;

export type A11yfyEnvironment = typeof A11yfyEnvironment.Default;
