// This file was auto-generated by Fern from our API Definition.

export interface ApiError {
    /** Machine-readable error code */
    code: string;
    /** Human-readable error message (English) */
    message: string;
}
