// This file was auto-generated by Fern from our API Definition.

export interface BalanceResponse {
    /** Total available credit balance */
    credits: number;
    /** Credits from active subscriptions */
    subscription: number;
    /** Credits from one-time purchases */
    one_time: number;
}
