// This file was auto-generated by Fern from our API Definition.

export interface CertificateInfo {
    /** Certificate identifier */
    certificate_id: string;
    /** Job that produced the certified output (null for detached certificates) */
    job_id: string | null;
    /** ISO 8601 issuance timestamp */
    issued_at: string;
    /** Remediation type the certificate attests */
    treatment: CertificateInfo.Treatment;
    /** Page count of the certified document */
    page_count: number | null;
    /** SHA-256 of the certified (remediated) PDF — matches the file byte-for-byte */
    output_sha256: string;
    /** Identifier of a newer certificate that replaces this one (after re-edit/regeneration). Null = this certificate is current. */
    superseded_by: string | null;
    /** Stable URL to download the certificate PDF (Bearer API key required) */
    download_url: string;
    /** Public verification page for this certificate (no auth required) */
    verify_url: string;
}

export namespace CertificateInfo {
    /** Remediation type the certificate attests */
    export const Treatment = {
        Technical: "technical",
        Full: "full",
    } as const;
    export type Treatment = (typeof Treatment)[keyof typeof Treatment];
}
