// This file was auto-generated by Fern from our API Definition.

import type * as A11yfy from "../index.js";

export interface CertificateListResponse {
    /** Matching certificates, newest first. The first entry with superseded_by = null is the current one. */
    certificates: A11yfy.CertificateInfo[];
}
