// This file was auto-generated by Fern from our API Definition.

export interface JobAcceptedResponse {
    /** Unique job identifier */
    job_id: string;
    /** Current job status. 'partial' is terminal: some documents of the job succeeded, others failed. */
    status: JobAcceptedResponse.Status;
    /** ISO 8601 creation timestamp */
    created_at: string;
    /** Present only when this request's `webhook_url` created the webhook configuration for the API key for the first time. Store the `signing_secret` now — the API returns it only once (it also remains visible in the web UI under Settings → Organization → API keys). */
    webhook?: (JobAcceptedResponse.Webhook | null) | undefined;
}

export namespace JobAcceptedResponse {
    /** Current job status. 'partial' is terminal: some documents of the job succeeded, others failed. */
    export const Status = {
        Pending: "pending",
        Processing: "processing",
        Done: "done",
        Failed: "failed",
        Partial: "partial",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];

    /**
     * Present only when this request's `webhook_url` created the webhook configuration for the API key for the first time. Store the `signing_secret` now — the API returns it only once (it also remains visible in the web UI under Settings → Organization → API keys).
     */
    export interface Webhook {
        /** Secret used to sign webhook deliveries (HMAC-SHA256, `X-A11yfy-Signature: ts;h1`) */
        signing_secret: string;
    }
}
