// This file was auto-generated by Fern from our API Definition.

export interface JobAcceptedResponse {
    /** Unique job identifier */
    job_id: string;
    /** Current job status. 'partial' is terminal: some documents of the job succeeded, others failed. */
    status: JobAcceptedResponse.Status;
    /** ISO 8601 creation timestamp */
    created_at: string;
}

export namespace JobAcceptedResponse {
    /** Current job status. 'partial' is terminal: some documents of the job succeeded, others failed. */
    export const Status = {
        Pending: "pending",
        Processing: "processing",
        Done: "done",
        Failed: "failed",
        Partial: "partial",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
