// This file was auto-generated by Fern from our API Definition.

export interface JobAlreadyValidResponse {
    /** Unique job identifier */
    job_id: string;
    /** Always 'done' — the job is terminal immediately */
    status: JobAlreadyValidResponse.Status;
    /** The uploaded PDF was already PDF/UA compliant; nothing was modified and no credits were consumed */
    already_valid: boolean;
    /** ISO 8601 creation timestamp */
    created_at: string;
}

export namespace JobAlreadyValidResponse {
    /** Always 'done' — the job is terminal immediately */
    export const Status = {
        Done: "done",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
