// This file was auto-generated by Fern from our API Definition.

import type * as A11yfy from "../index.js";

export interface JobListResponse {
    /** Jobs of the organization, newest first */
    jobs: A11yfy.JobListItem[];
    /** Opaque pagination cursor — pass as ?cursor= to fetch the next page. Null when there are no more results. */
    next_cursor: string | null;
}
