// This file was auto-generated by Fern from our API Definition.

export interface JobListItem {
    /** Unique job identifier */
    job_id: string;
    /** Current job status. 'partial' is terminal: some documents of the job succeeded, others failed. */
    status: JobListItem.Status;
    /** ISO 8601 creation timestamp */
    created_at: string;
    /** Original filename of the uploaded PDF (null for legacy jobs) */
    filename: string | null;
    /** Credits consumed (null until quoted) */
    credits_used: number | null;
    /** Remediation type applied: 'technical' (lower-cost tag-level repair), 'full' (complete rebuild), or 'noop' (document was already compliant). */
    treatment?: JobListItem.Treatment | undefined;
}

export namespace JobListItem {
    /** Current job status. 'partial' is terminal: some documents of the job succeeded, others failed. */
    export const Status = {
        Pending: "pending",
        Processing: "processing",
        Done: "done",
        Failed: "failed",
        Partial: "partial",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
    /** Remediation type applied: 'technical' (lower-cost tag-level repair), 'full' (complete rebuild), or 'noop' (document was already compliant). */
    export const Treatment = {
        Technical: "technical",
        Full: "full",
        Noop: "noop",
    } as const;
    export type Treatment = (typeof Treatment)[keyof typeof Treatment];
}
