// This file was auto-generated by Fern from our API Definition.

export interface JobResultResponse {
    /** Unique job identifier */
    job_id: string;
    /** Job status. Terminal values: 'done', 'failed', 'partial' (mixed multi-document outcome). */
    status: JobResultResponse.Status;
    /** Actual credits consumed */
    credits_used: number;
    /** Remediation type applied: 'technical' (lower-cost tag-level repair), 'full' (complete rebuild), or 'noop' (document was already compliant). */
    treatment?: JobResultResponse.Treatment | undefined;
    /** Presigned URL to the remediated PDF (may expire) */
    output_url: string | null;
    /** Pre-remediation diagnostic summary */
    before?: JobResultResponse.Before | undefined;
    /** Post-remediation diagnostic summary */
    after?: JobResultResponse.After | undefined;
    /** Compliance certificate for the remediated output. Present only when the output passed machine validation (veraPDF) and a certificate was issued. */
    certificate?: JobResultResponse.Certificate | undefined;
}

export namespace JobResultResponse {
    /** Job status. Terminal values: 'done', 'failed', 'partial' (mixed multi-document outcome). */
    export const Status = {
        Done: "done",
        Failed: "failed",
        Partial: "partial",
        Pending: "pending",
        Processing: "processing",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
    /** Remediation type applied: 'technical' (lower-cost tag-level repair), 'full' (complete rebuild), or 'noop' (document was already compliant). */
    export const Treatment = {
        Technical: "technical",
        Full: "full",
        Noop: "noop",
    } as const;
    export type Treatment = (typeof Treatment)[keyof typeof Treatment];

    /**
     * Pre-remediation diagnostic summary
     */
    export interface Before {
        issues?: number | undefined;
        pages?: number | undefined;
    }

    /**
     * Post-remediation diagnostic summary
     */
    export interface After {
        issues?: number | undefined;
        pages?: number | undefined;
    }

    /**
     * Compliance certificate for the remediated output. Present only when the output passed machine validation (veraPDF) and a certificate was issued.
     */
    export interface Certificate {
        /** Compliance certificate identifier */
        certificate_id: string;
        /** Stable URL to download the certificate PDF (Bearer API key required) */
        download_url: string;
        /** Public verification page for this certificate (no auth required) */
        verify_url: string;
    }
}
