// This file was auto-generated by Fern from our API Definition.

export interface JobStatusResponse {
    /** Unique job identifier */
    job_id: string;
    /** Current job status. 'partial' is terminal: some documents of the job succeeded, others failed. */
    status: JobStatusResponse.Status;
    /** Credits consumed (null until done) */
    credits_used: number | null;
    /** Error details if status is "failed" */
    error?: (JobStatusResponse.Error_ | null) | undefined;
}

export namespace JobStatusResponse {
    /** Current job status. 'partial' is terminal: some documents of the job succeeded, others failed. */
    export const Status = {
        Pending: "pending",
        Processing: "processing",
        Done: "done",
        Failed: "failed",
        Partial: "partial",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];

    /**
     * Error details if status is "failed"
     */
    export interface Error_ {
        code: string;
        message: string;
    }
}
