// This file was auto-generated by Fern from our API Definition.

export interface UsageItem {
    /** Job identifier */
    job_id: string;
    /** Credits consumed by this job */
    credits_used: number;
    /** Job creation timestamp */
    created_at: string;
    /** Remediation type applied: 'technical' (lower-cost tag-level repair), 'full' (complete rebuild), or 'noop' (document was already compliant). */
    treatment?: UsageItem.Treatment | undefined;
}

export namespace UsageItem {
    /** Remediation type applied: 'technical' (lower-cost tag-level repair), 'full' (complete rebuild), or 'noop' (document was already compliant). */
    export const Treatment = {
        Technical: "technical",
        Full: "full",
        Noop: "noop",
    } as const;
    export type Treatment = (typeof Treatment)[keyof typeof Treatment];
}
