// This file was auto-generated by Fern from our API Definition.

import type * as A11yfy from "../index.js";

export interface UsageResponse {
    /** List of past jobs with credit consumption */
    items: A11yfy.UsageItem[];
}
