// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         certId: "certId"
 *     }
 */
export interface DownloadCertificateRequest {
    /** Certificate identifier */
    certId: string;
}
