// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface FindCertificatesRequest {
    /** Job identifier from POST /v1/jobs response */
    job_id?: string;
    /** SHA-256 hash (lowercase hex) of the remediated PDF file */
    output_sha256?: string;
}
