// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         certId: "A11Y-2026-07-3F9K2M"
 *     }
 */
export interface GetCertificateRequest {
    /** Certificate identifier */
    certId: string;
}
