# This file was auto-generated by Fern from our API Definition.

import typing

from .. import core
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.job_already_valid_response import JobAlreadyValidResponse
from ..types.job_list_response import JobListResponse
from ..types.job_result_response import JobResultResponse
from ..types.job_status_response import JobStatusResponse
from .raw_client import AsyncRawJobsClient, RawJobsClient
from .types.list_jobs_request_status import ListJobsRequestStatus

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class JobsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawJobsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawJobsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawJobsClient
        """
        return self._raw_client

    def list_jobs(
        self,
        *,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        status: typing.Optional[ListJobsRequestStatus] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> JobListResponse:
        """
        Returns the jobs of the organization, newest first, with cursor-based
        pagination. Pass the returned `next_cursor` as `?cursor=` to fetch the
        next page; `next_cursor: null` means there are no more results.

        Parameters
        ----------
        limit : typing.Optional[int]
            Page size (1–100, default 20)

        cursor : typing.Optional[str]
            Opaque pagination cursor from a previous response

        status : typing.Optional[ListJobsRequestStatus]
            Filter by job status

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        JobListResponse
            Paginated job list

        Examples
        --------
        from a11yfy import BaseA11yfy

        client = BaseA11yfy(
            token="YOUR_TOKEN",
        )
        client.jobs.list_jobs()
        """
        _response = self._raw_client.list_jobs(
            limit=limit, cursor=cursor, status=status, request_options=request_options
        )
        return _response.data

    def create_job(
        self,
        *,
        idempotency_key: str,
        file: typing.Optional[core.File] = OMIT,
        webhook_url: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> JobAlreadyValidResponse:
        """
        Single call that launches the full remediation pipeline:
        diagnostics → credit reservation → processing.
        Returns a `job_id` immediately for status polling.

        Parameters
        ----------
        idempotency_key : str
            Required deduplication key (max 256 chars). Reusing the same key within 24 hours replays the stored successful response (200/202). Error responses (4xx/5xx) are never stored, so a failed request can be retried safely with the same key.

        file : typing.Optional[core.File]
            See core.File for more documentation

        webhook_url : typing.Optional[str]
            Optional callback URL for HMAC-signed completion webhook

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        JobAlreadyValidResponse
            Document already compliant — no processing started, no credits consumed. The job is created in terminal `done` state; `GET /v1/jobs/{id}/result` returns `treatment: "noop"`, `already_valid: true` and `output_url: null`.

        Examples
        --------
        from a11yfy import BaseA11yfy

        client = BaseA11yfy(
            token="YOUR_TOKEN",
        )
        client.jobs.create_job(
            idempotency_key="550e8400-e29b-41d4-a716-446655440000",
        )
        """
        _response = self._raw_client.create_job(
            idempotency_key=idempotency_key, file=file, webhook_url=webhook_url, request_options=request_options
        )
        return _response.data

    def get_job(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> JobStatusResponse:
        """
        Returns the current job status: `pending`, `processing`, `done`, or `failed`.
        Can be polled during processing.

        Parameters
        ----------
        id : str
            Job identifier from POST /v1/jobs response

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        JobStatusResponse
            Job status

        Examples
        --------
        from a11yfy import BaseA11yfy

        client = BaseA11yfy(
            token="YOUR_TOKEN",
        )
        client.jobs.get_job(
            id="id",
        )
        """
        _response = self._raw_client.get_job(id, request_options=request_options)
        return _response.data

    def get_job_result(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> JobResultResponse:
        """
        Returns the completed job result: output URL, credits consumed,
        pre/post remediation diagnostics.

        Parameters
        ----------
        id : str
            Job identifier from POST /v1/jobs response

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        JobResultResponse
            Job result

        Examples
        --------
        from a11yfy import BaseA11yfy

        client = BaseA11yfy(
            token="YOUR_TOKEN",
        )
        client.jobs.get_job_result(
            id="id",
        )
        """
        _response = self._raw_client.get_job_result(id, request_options=request_options)
        return _response.data


class AsyncJobsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawJobsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawJobsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawJobsClient
        """
        return self._raw_client

    async def list_jobs(
        self,
        *,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        status: typing.Optional[ListJobsRequestStatus] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> JobListResponse:
        """
        Returns the jobs of the organization, newest first, with cursor-based
        pagination. Pass the returned `next_cursor` as `?cursor=` to fetch the
        next page; `next_cursor: null` means there are no more results.

        Parameters
        ----------
        limit : typing.Optional[int]
            Page size (1–100, default 20)

        cursor : typing.Optional[str]
            Opaque pagination cursor from a previous response

        status : typing.Optional[ListJobsRequestStatus]
            Filter by job status

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        JobListResponse
            Paginated job list

        Examples
        --------
        import asyncio

        from a11yfy import AsyncBaseA11yfy

        client = AsyncBaseA11yfy(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.jobs.list_jobs()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_jobs(
            limit=limit, cursor=cursor, status=status, request_options=request_options
        )
        return _response.data

    async def create_job(
        self,
        *,
        idempotency_key: str,
        file: typing.Optional[core.File] = OMIT,
        webhook_url: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> JobAlreadyValidResponse:
        """
        Single call that launches the full remediation pipeline:
        diagnostics → credit reservation → processing.
        Returns a `job_id` immediately for status polling.

        Parameters
        ----------
        idempotency_key : str
            Required deduplication key (max 256 chars). Reusing the same key within 24 hours replays the stored successful response (200/202). Error responses (4xx/5xx) are never stored, so a failed request can be retried safely with the same key.

        file : typing.Optional[core.File]
            See core.File for more documentation

        webhook_url : typing.Optional[str]
            Optional callback URL for HMAC-signed completion webhook

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        JobAlreadyValidResponse
            Document already compliant — no processing started, no credits consumed. The job is created in terminal `done` state; `GET /v1/jobs/{id}/result` returns `treatment: "noop"`, `already_valid: true` and `output_url: null`.

        Examples
        --------
        import asyncio

        from a11yfy import AsyncBaseA11yfy

        client = AsyncBaseA11yfy(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.jobs.create_job(
                idempotency_key="550e8400-e29b-41d4-a716-446655440000",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_job(
            idempotency_key=idempotency_key, file=file, webhook_url=webhook_url, request_options=request_options
        )
        return _response.data

    async def get_job(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> JobStatusResponse:
        """
        Returns the current job status: `pending`, `processing`, `done`, or `failed`.
        Can be polled during processing.

        Parameters
        ----------
        id : str
            Job identifier from POST /v1/jobs response

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        JobStatusResponse
            Job status

        Examples
        --------
        import asyncio

        from a11yfy import AsyncBaseA11yfy

        client = AsyncBaseA11yfy(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.jobs.get_job(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_job(id, request_options=request_options)
        return _response.data

    async def get_job_result(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> JobResultResponse:
        """
        Returns the completed job result: output URL, credits consumed,
        pre/post remediation diagnostics.

        Parameters
        ----------
        id : str
            Job identifier from POST /v1/jobs response

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        JobResultResponse
            Job result

        Examples
        --------
        import asyncio

        from a11yfy import AsyncBaseA11yfy

        client = AsyncBaseA11yfy(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.jobs.get_job_result(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_job_result(id, request_options=request_options)
        return _response.data
