// This file was auto-generated by Fern from our API Definition.

/** Filter by job status */
export const ListJobsRequestStatus = {
    Pending: "pending",
    Processing: "processing",
    Done: "done",
    Failed: "failed",
    Partial: "partial",
} as const;
export type ListJobsRequestStatus = (typeof ListJobsRequestStatus)[keyof typeof ListJobsRequestStatus];
