# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.certificate_info import CertificateInfo
from ..types.certificate_list_response import CertificateListResponse
from .raw_client import AsyncRawCertificatesClient, RawCertificatesClient


class CertificatesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawCertificatesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawCertificatesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawCertificatesClient
        """
        return self._raw_client

    def find_certificates(
        self,
        *,
        job_id: typing.Optional[str] = None,
        output_sha256: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CertificateListResponse:
        """
        Looks up compliance certificates by the job that produced them
        (`job_id`) or by the SHA-256 of the remediated PDF (`output_sha256`).
        Provide exactly one of the two parameters. Returns the full supersede
        chain, newest first — the entry with `superseded_by: null` is current.

        Parameters
        ----------
        job_id : typing.Optional[str]
            Job identifier from POST /v1/jobs response

        output_sha256 : typing.Optional[str]
            SHA-256 hash (lowercase hex) of the remediated PDF file

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CertificateListResponse
            Matching certificates (empty array when none exist)

        Examples
        --------
        from a11yfy import BaseA11yfy

        client = BaseA11yfy(
            token="YOUR_TOKEN",
        )
        client.certificates.find_certificates()
        """
        _response = self._raw_client.find_certificates(
            job_id=job_id, output_sha256=output_sha256, request_options=request_options
        )
        return _response.data

    def get_certificate(
        self, cert_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> CertificateInfo:
        """
        Returns the metadata of a single compliance certificate, including its
        download and public verification URLs.

        Parameters
        ----------
        cert_id : str
            Certificate identifier

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CertificateInfo
            Certificate metadata

        Examples
        --------
        from a11yfy import BaseA11yfy

        client = BaseA11yfy(
            token="YOUR_TOKEN",
        )
        client.certificates.get_certificate(
            cert_id="A11Y-2026-07-3F9K2M",
        )
        """
        _response = self._raw_client.get_certificate(cert_id, request_options=request_options)
        return _response.data

    def download_certificate(
        self, cert_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Iterator[bytes]:
        """
        Streams the certificate as a PDF/UA-compliant PDF file. The file is
        immutable: re-issued certificates get a new identifier, the old file
        never changes.

        Parameters
        ----------
        cert_id : str
            Certificate identifier

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration. You can pass in configuration such as `chunk_size`, and more to customize the request and response.

        Returns
        -------
        typing.Iterator[bytes]
            Certificate PDF

        Examples
        --------
        from a11yfy import BaseA11yfy

        client = BaseA11yfy(
            token="YOUR_TOKEN",
        )
        client.certificates.download_certificate(
            cert_id="certId",
        )
        """
        with self._raw_client.download_certificate(cert_id, request_options=request_options) as r:
            yield from r.data


class AsyncCertificatesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawCertificatesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawCertificatesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawCertificatesClient
        """
        return self._raw_client

    async def find_certificates(
        self,
        *,
        job_id: typing.Optional[str] = None,
        output_sha256: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CertificateListResponse:
        """
        Looks up compliance certificates by the job that produced them
        (`job_id`) or by the SHA-256 of the remediated PDF (`output_sha256`).
        Provide exactly one of the two parameters. Returns the full supersede
        chain, newest first — the entry with `superseded_by: null` is current.

        Parameters
        ----------
        job_id : typing.Optional[str]
            Job identifier from POST /v1/jobs response

        output_sha256 : typing.Optional[str]
            SHA-256 hash (lowercase hex) of the remediated PDF file

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CertificateListResponse
            Matching certificates (empty array when none exist)

        Examples
        --------
        import asyncio

        from a11yfy import AsyncBaseA11yfy

        client = AsyncBaseA11yfy(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.certificates.find_certificates()


        asyncio.run(main())
        """
        _response = await self._raw_client.find_certificates(
            job_id=job_id, output_sha256=output_sha256, request_options=request_options
        )
        return _response.data

    async def get_certificate(
        self, cert_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> CertificateInfo:
        """
        Returns the metadata of a single compliance certificate, including its
        download and public verification URLs.

        Parameters
        ----------
        cert_id : str
            Certificate identifier

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CertificateInfo
            Certificate metadata

        Examples
        --------
        import asyncio

        from a11yfy import AsyncBaseA11yfy

        client = AsyncBaseA11yfy(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.certificates.get_certificate(
                cert_id="A11Y-2026-07-3F9K2M",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_certificate(cert_id, request_options=request_options)
        return _response.data

    async def download_certificate(
        self, cert_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.AsyncIterator[bytes]:
        """
        Streams the certificate as a PDF/UA-compliant PDF file. The file is
        immutable: re-issued certificates get a new identifier, the old file
        never changes.

        Parameters
        ----------
        cert_id : str
            Certificate identifier

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration. You can pass in configuration such as `chunk_size`, and more to customize the request and response.

        Returns
        -------
        typing.AsyncIterator[bytes]
            Certificate PDF

        Examples
        --------
        import asyncio

        from a11yfy import AsyncBaseA11yfy

        client = AsyncBaseA11yfy(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.certificates.download_certificate(
                cert_id="certId",
            )


        asyncio.run(main())
        """
        async with self._raw_client.download_certificate(cert_id, request_options=request_options) as r:
            async for _chunk in r.data:
                yield _chunk
