# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .api_error import ApiError
    from .balance_response import BalanceResponse
    from .certificate_info import CertificateInfo
    from .certificate_info_treatment import CertificateInfoTreatment
    from .certificate_list_response import CertificateListResponse
    from .job_accepted_response import JobAcceptedResponse
    from .job_accepted_response_status import JobAcceptedResponseStatus
    from .job_list_item import JobListItem
    from .job_list_item_status import JobListItemStatus
    from .job_list_item_treatment import JobListItemTreatment
    from .job_list_response import JobListResponse
    from .job_result_response import JobResultResponse
    from .job_result_response_after import JobResultResponseAfter
    from .job_result_response_before import JobResultResponseBefore
    from .job_result_response_certificate import JobResultResponseCertificate
    from .job_result_response_status import JobResultResponseStatus
    from .job_result_response_treatment import JobResultResponseTreatment
    from .job_status_response import JobStatusResponse
    from .job_status_response_error import JobStatusResponseError
    from .job_status_response_status import JobStatusResponseStatus
    from .usage_item import UsageItem
    from .usage_item_treatment import UsageItemTreatment
    from .usage_response import UsageResponse
_dynamic_imports: typing.Dict[str, str] = {
    "ApiError": ".api_error",
    "BalanceResponse": ".balance_response",
    "CertificateInfo": ".certificate_info",
    "CertificateInfoTreatment": ".certificate_info_treatment",
    "CertificateListResponse": ".certificate_list_response",
    "JobAcceptedResponse": ".job_accepted_response",
    "JobAcceptedResponseStatus": ".job_accepted_response_status",
    "JobListItem": ".job_list_item",
    "JobListItemStatus": ".job_list_item_status",
    "JobListItemTreatment": ".job_list_item_treatment",
    "JobListResponse": ".job_list_response",
    "JobResultResponse": ".job_result_response",
    "JobResultResponseAfter": ".job_result_response_after",
    "JobResultResponseBefore": ".job_result_response_before",
    "JobResultResponseCertificate": ".job_result_response_certificate",
    "JobResultResponseStatus": ".job_result_response_status",
    "JobResultResponseTreatment": ".job_result_response_treatment",
    "JobStatusResponse": ".job_status_response",
    "JobStatusResponseError": ".job_status_response_error",
    "JobStatusResponseStatus": ".job_status_response_status",
    "UsageItem": ".usage_item",
    "UsageItemTreatment": ".usage_item_treatment",
    "UsageResponse": ".usage_response",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "ApiError",
    "BalanceResponse",
    "CertificateInfo",
    "CertificateInfoTreatment",
    "CertificateListResponse",
    "JobAcceptedResponse",
    "JobAcceptedResponseStatus",
    "JobListItem",
    "JobListItemStatus",
    "JobListItemTreatment",
    "JobListResponse",
    "JobResultResponse",
    "JobResultResponseAfter",
    "JobResultResponseBefore",
    "JobResultResponseCertificate",
    "JobResultResponseStatus",
    "JobResultResponseTreatment",
    "JobStatusResponse",
    "JobStatusResponseError",
    "JobStatusResponseStatus",
    "UsageItem",
    "UsageItemTreatment",
    "UsageResponse",
]
