# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel


class ApiError(UniversalBaseModel):
    code: str = pydantic.Field()
    """
    Machine-readable error code
    """

    message: str = pydantic.Field()
    """
    Human-readable error message (English)
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
