# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel


class BalanceResponse(UniversalBaseModel):
    credits: int = pydantic.Field()
    """
    Total available credit balance
    """

    subscription: int = pydantic.Field()
    """
    Credits from active subscriptions
    """

    one_time: int = pydantic.Field()
    """
    Credits from one-time purchases
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
