# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .certificate_info_treatment import CertificateInfoTreatment


class CertificateInfo(UniversalBaseModel):
    certificate_id: str = pydantic.Field()
    """
    Certificate identifier
    """

    job_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Job that produced the certified output (null for detached certificates)
    """

    issued_at: dt.datetime = pydantic.Field()
    """
    ISO 8601 issuance timestamp
    """

    treatment: CertificateInfoTreatment = pydantic.Field()
    """
    Remediation type the certificate attests
    """

    page_count: typing.Optional[int] = pydantic.Field(default=None)
    """
    Page count of the certified document
    """

    output_sha256: str = pydantic.Field()
    """
    SHA-256 of the certified (remediated) PDF — matches the file byte-for-byte
    """

    superseded_by: typing.Optional[str] = pydantic.Field(default=None)
    """
    Identifier of a newer certificate that replaces this one (after re-edit/regeneration). Null = this certificate is current.
    """

    download_url: str = pydantic.Field()
    """
    Stable URL to download the certificate PDF (Bearer API key required)
    """

    verify_url: str = pydantic.Field()
    """
    Public verification page for this certificate (no auth required)
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
