# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .certificate_info import CertificateInfo


class CertificateListResponse(UniversalBaseModel):
    certificates: typing.List[CertificateInfo] = pydantic.Field()
    """
    Matching certificates, newest first. The first entry with superseded_by = null is the current one.
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
