# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .job_status_response_error import JobStatusResponseError
from .job_status_response_status import JobStatusResponseStatus


class JobStatusResponse(UniversalBaseModel):
    job_id: str = pydantic.Field()
    """
    Unique job identifier
    """

    status: JobStatusResponseStatus = pydantic.Field()
    """
    Current job status. 'partial' is terminal: some documents of the job succeeded, others failed.
    """

    credits_used: typing.Optional[int] = pydantic.Field(default=None)
    """
    Credits consumed (null until done)
    """

    error: typing.Optional[JobStatusResponseError] = pydantic.Field(default=None)
    """
    Error details if status is "failed"
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
