# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .job_list_item import JobListItem


class JobListResponse(UniversalBaseModel):
    jobs: typing.List[JobListItem] = pydantic.Field()
    """
    Jobs of the organization, newest first
    """

    next_cursor: typing.Optional[str] = pydantic.Field(default=None)
    """
    Opaque pagination cursor — pass as ?cursor= to fetch the next page. Null when there are no more results.
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
