# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .job_already_valid_response_status import JobAlreadyValidResponseStatus


class JobAlreadyValidResponse(UniversalBaseModel):
    job_id: str = pydantic.Field()
    """
    Unique job identifier
    """

    status: JobAlreadyValidResponseStatus = pydantic.Field()
    """
    Always 'done' — the job is terminal immediately
    """

    already_valid: bool = pydantic.Field()
    """
    The uploaded PDF was already PDF/UA compliant; nothing was modified and no credits were consumed
    """

    created_at: dt.datetime = pydantic.Field()
    """
    ISO 8601 creation timestamp
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
