# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .job_list_item_status import JobListItemStatus
from .job_list_item_treatment import JobListItemTreatment


class JobListItem(UniversalBaseModel):
    job_id: str = pydantic.Field()
    """
    Unique job identifier
    """

    status: JobListItemStatus = pydantic.Field()
    """
    Current job status. 'partial' is terminal: some documents of the job succeeded, others failed.
    """

    created_at: dt.datetime = pydantic.Field()
    """
    ISO 8601 creation timestamp
    """

    filename: typing.Optional[str] = pydantic.Field(default=None)
    """
    Original filename of the uploaded PDF (null for legacy jobs)
    """

    credits_used: typing.Optional[int] = pydantic.Field(default=None)
    """
    Credits consumed (null until quoted)
    """

    treatment: typing.Optional[JobListItemTreatment] = pydantic.Field(default=None)
    """
    Remediation type applied: 'technical' (lower-cost tag-level repair), 'full' (complete rebuild), or 'noop' (document was already compliant).
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
