# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .job_accepted_response_status import JobAcceptedResponseStatus
from .job_accepted_response_webhook import JobAcceptedResponseWebhook


class JobAcceptedResponse(UniversalBaseModel):
    job_id: str = pydantic.Field()
    """
    Unique job identifier
    """

    status: JobAcceptedResponseStatus = pydantic.Field()
    """
    Current job status. 'partial' is terminal: some documents of the job succeeded, others failed.
    """

    created_at: dt.datetime = pydantic.Field()
    """
    ISO 8601 creation timestamp
    """

    webhook: typing.Optional[JobAcceptedResponseWebhook] = pydantic.Field(default=None)
    """
    Present only when this request's `webhook_url` created the webhook configuration for the API key for the first time. Store the `signing_secret` now — the API returns it only once (it also remains visible in the web UI under Settings → Organization → API keys).
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
