# This file was auto-generated by Fern from our API Definition.

import typing

JobStatusResponseStatus = typing.Union[typing.Literal["pending", "processing", "done", "failed", "partial"], typing.Any]
