# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .job_accepted_response_status import JobAcceptedResponseStatus


class JobAcceptedResponse(UniversalBaseModel):
    job_id: str = pydantic.Field()
    """
    Unique job identifier
    """

    status: JobAcceptedResponseStatus = pydantic.Field()
    """
    Current job status. 'partial' is terminal: some documents of the job succeeded, others failed.
    """

    created_at: dt.datetime = pydantic.Field()
    """
    ISO 8601 creation timestamp
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
