# This file was auto-generated by Fern from our API Definition.

import typing

JobAcceptedResponseStatus = typing.Union[
    typing.Literal["pending", "processing", "done", "failed", "partial"], typing.Any
]
