# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel


class JobAcceptedResponseWebhook(UniversalBaseModel):
    """
    Present only when this request's `webhook_url` created the webhook configuration for the API key for the first time. Store the `signing_secret` now — the API returns it only once (it also remains visible in the web UI under Settings → Organization → API keys).
    """

    signing_secret: str = pydantic.Field()
    """
    Secret used to sign webhook deliveries (HMAC-SHA256, `X-A11yfy-Signature: ts;h1`)
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
