# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .usage_item import UsageItem


class UsageResponse(UniversalBaseModel):
    items: typing.List[UsageItem] = pydantic.Field()
    """
    List of past jobs with credit consumption
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
