# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .usage_item_treatment import UsageItemTreatment


class UsageItem(UniversalBaseModel):
    job_id: str = pydantic.Field()
    """
    Job identifier
    """

    credits_used: int = pydantic.Field()
    """
    Credits consumed by this job
    """

    created_at: dt.datetime = pydantic.Field()
    """
    Job creation timestamp
    """

    treatment: typing.Optional[UsageItemTreatment] = pydantic.Field(default=None)
    """
    Remediation type applied: 'technical' (lower-cost tag-level repair), 'full' (complete rebuild), or 'noop' (document was already compliant).
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
