# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.balance_response import BalanceResponse
from ..types.usage_response import UsageResponse
from .raw_client import AsyncRawBillingClient, RawBillingClient


class BillingClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawBillingClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawBillingClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawBillingClient
        """
        return self._raw_client

    def get_balance(self, *, request_options: typing.Optional[RequestOptions] = None) -> BalanceResponse:
        """
        Returns the organization's current credit balance with breakdown:
        subscription credits, one-time purchase credits, and total.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BalanceResponse
            Credit balance

        Examples
        --------
        from a11yfy import BaseA11yfy

        client = BaseA11yfy(
            token="YOUR_TOKEN",
        )
        client.billing.get_balance()
        """
        _response = self._raw_client.get_balance(request_options=request_options)
        return _response.data

    def get_usage(self, *, request_options: typing.Optional[RequestOptions] = None) -> UsageResponse:
        """
        Returns the list of past jobs with credit consumption and timestamps.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UsageResponse
            Usage history

        Examples
        --------
        from a11yfy import BaseA11yfy

        client = BaseA11yfy(
            token="YOUR_TOKEN",
        )
        client.billing.get_usage()
        """
        _response = self._raw_client.get_usage(request_options=request_options)
        return _response.data


class AsyncBillingClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawBillingClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawBillingClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawBillingClient
        """
        return self._raw_client

    async def get_balance(self, *, request_options: typing.Optional[RequestOptions] = None) -> BalanceResponse:
        """
        Returns the organization's current credit balance with breakdown:
        subscription credits, one-time purchase credits, and total.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BalanceResponse
            Credit balance

        Examples
        --------
        import asyncio

        from a11yfy import AsyncBaseA11yfy

        client = AsyncBaseA11yfy(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.billing.get_balance()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_balance(request_options=request_options)
        return _response.data

    async def get_usage(self, *, request_options: typing.Optional[RequestOptions] = None) -> UsageResponse:
        """
        Returns the list of past jobs with credit consumption and timestamps.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UsageResponse
            Usage history

        Examples
        --------
        import asyncio

        from a11yfy import AsyncBaseA11yfy

        client = AsyncBaseA11yfy(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.billing.get_usage()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_usage(request_options=request_options)
        return _response.data
