# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .types import (
        ApiError,
        BalanceResponse,
        CertificateInfo,
        CertificateInfoTreatment,
        CertificateListResponse,
        JobAcceptedResponse,
        JobAcceptedResponseStatus,
        JobListItem,
        JobListItemStatus,
        JobListItemTreatment,
        JobListResponse,
        JobResultResponse,
        JobResultResponseAfter,
        JobResultResponseBefore,
        JobResultResponseCertificate,
        JobResultResponseStatus,
        JobResultResponseTreatment,
        JobStatusResponse,
        JobStatusResponseError,
        JobStatusResponseStatus,
        UsageItem,
        UsageItemTreatment,
        UsageResponse,
    )
    from .errors import BadRequestError, NotFoundError, PaymentRequiredError, TooManyRequestsError, UnauthorizedError
    from . import billing, certificates, jobs
    from ._default_clients import DefaultAioHttpClient, DefaultAsyncHttpxClient
    from .client import AsyncBaseA11yfy, BaseA11yfy
    from .custom_client import A11yfy, AsyncA11yfy, JobFailedError, RemediationTimeoutError
    from .environment import BaseA11yfyEnvironment
    from .jobs import ListJobsRequestStatus
    from .webhooks import Webhook, WebhookEvent, WebhookVerificationError
_dynamic_imports: typing.Dict[str, str] = {
    "A11yfy": ".custom_client",
    "ApiError": ".types",
    "AsyncA11yfy": ".custom_client",
    "AsyncBaseA11yfy": ".client",
    "BadRequestError": ".errors",
    "BalanceResponse": ".types",
    "BaseA11yfy": ".client",
    "BaseA11yfyEnvironment": ".environment",
    "CertificateInfo": ".types",
    "CertificateInfoTreatment": ".types",
    "CertificateListResponse": ".types",
    "DefaultAioHttpClient": "._default_clients",
    "DefaultAsyncHttpxClient": "._default_clients",
    "JobAcceptedResponse": ".types",
    "JobAcceptedResponseStatus": ".types",
    "JobFailedError": ".custom_client",
    "JobListItem": ".types",
    "JobListItemStatus": ".types",
    "JobListItemTreatment": ".types",
    "JobListResponse": ".types",
    "JobResultResponse": ".types",
    "JobResultResponseAfter": ".types",
    "JobResultResponseBefore": ".types",
    "JobResultResponseCertificate": ".types",
    "JobResultResponseStatus": ".types",
    "JobResultResponseTreatment": ".types",
    "JobStatusResponse": ".types",
    "JobStatusResponseError": ".types",
    "JobStatusResponseStatus": ".types",
    "ListJobsRequestStatus": ".jobs",
    "NotFoundError": ".errors",
    "PaymentRequiredError": ".errors",
    "RemediationTimeoutError": ".custom_client",
    "TooManyRequestsError": ".errors",
    "UnauthorizedError": ".errors",
    "UsageItem": ".types",
    "UsageItemTreatment": ".types",
    "UsageResponse": ".types",
    "Webhook": ".webhooks",
    "WebhookEvent": ".webhooks",
    "WebhookVerificationError": ".webhooks",
    "billing": ".billing",
    "certificates": ".certificates",
    "jobs": ".jobs",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "A11yfy",
    "ApiError",
    "AsyncA11yfy",
    "AsyncBaseA11yfy",
    "BadRequestError",
    "BalanceResponse",
    "BaseA11yfy",
    "BaseA11yfyEnvironment",
    "CertificateInfo",
    "CertificateInfoTreatment",
    "CertificateListResponse",
    "DefaultAioHttpClient",
    "DefaultAsyncHttpxClient",
    "JobAcceptedResponse",
    "JobAcceptedResponseStatus",
    "JobFailedError",
    "JobListItem",
    "JobListItemStatus",
    "JobListItemTreatment",
    "JobListResponse",
    "JobResultResponse",
    "JobResultResponseAfter",
    "JobResultResponseBefore",
    "JobResultResponseCertificate",
    "JobResultResponseStatus",
    "JobResultResponseTreatment",
    "JobStatusResponse",
    "JobStatusResponseError",
    "JobStatusResponseStatus",
    "ListJobsRequestStatus",
    "NotFoundError",
    "PaymentRequiredError",
    "RemediationTimeoutError",
    "TooManyRequestsError",
    "UnauthorizedError",
    "UsageItem",
    "UsageItemTreatment",
    "UsageResponse",
    "Webhook",
    "WebhookEvent",
    "WebhookVerificationError",
    "billing",
    "certificates",
    "jobs",
]
